version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "eu-west-2"
    IMAGE_TAG: "latest"
    IMAGE_REPO_NAME: "osbot-jupyter"
    ACCOUNT_ID: "244560807427"

phases:
  pre_build:
    commands:
      - echo $AWS_DEFAULT_REGION
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - echo "Build started on `date`"
      - docker build -t $IMAGE_REPO_NAME:latest builds/osbot-jupyer/.
      - docker tag $IMAGE_REPO_NAME:latest $ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$IMAGE_REPO_NAME:latest
