version: 0.1
environmentVariables:
  plaintext:
    AWS_DEFAULT_REGION: "west-2"
    #IMAGE_REPO_NAME: "GS-ECR-code-build"
    #IMAGE_TAG: "latest"
phases:
  pre_build:
    commands:
      - echo $AWS_DEFAULT_REGION
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      #- echo "- docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG ."
      - echo "Build started on `date`"
      - docker build -t gs-ecr-code-build:latest docker/.
      - docker tag gs-ecr-code-build:latest gs-ecr-code-build:latest


  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push gs-ecr-code-build:latest
#      - pip3 install pbx_gs_python_utils
#      - pip3 install python-coveralls pytest-cov==2.5.0
#      - pip3 install boto3 pytest
#      #- pip3 install elasticsearch
#      - git checkout master
#      - export COVERALLS_SERVICE_NAME=aws_code_build


#  post_build:
#    commands:
     # - echo "*** In post_build phase ***"
      #- cd tests && pytest -v --cov
      #- cp tests/.coverage .
      #- coveralls

    #finally:
    #  - echo "*** After post_build phase ***"